/**
 * Table des champions, générée depuis Data Dragon 16.18.1 (locale fr_FR).
 *
 * Elle sert à trois choses que l'API ne fait pas seule :
 *  - retrouver le fichier de public/lol/champions à partir du championName
 *    renvoyé par match-v5, dont la casse diffère parfois de la clé Data
 *    Dragon (le cas connu est FiddleSticks contre Fiddlesticks) ;
 *  - afficher un nom lisible : l'API renvoie MonkeyKing, le joueur lit
 *    « Wukong » ;
 *  - traduire l'identifiant numérique de champion, seul format renvoyé par
 *    spectator-v5 pour une partie en cours.
 *
 * Régénérer avec `npm run champions:sync`. Ne pas éditer à la main.
 */

export const CHAMPION_NAMES: Record<string, string> = {
  Aatrox: "Aatrox",
  Ahri: "Ahri",
  Akali: "Akali",
  Akshan: "Akshan",
  Alistar: "Alistar",
  Ambessa: "Ambessa",
  Amumu: "Amumu",
  Anivia: "Anivia",
  Annie: "Annie",
  Aphelios: "Aphelios",
  Ashe: "Ashe",
  AurelionSol: "Aurelion Sol",
  Aurora: "Aurora",
  Azir: "Azir",
  Bard: "Bard",
  Belveth: "Bel'Veth",
  Blitzcrank: "Blitzcrank",
  Brand: "Brand",
  Braum: "Braum",
  Briar: "Briar",
  Caitlyn: "Caitlyn",
  Camille: "Camille",
  Cassiopeia: "Cassiopeia",
  Chogath: "Cho'Gath",
  Corki: "Corki",
  Darius: "Darius",
  Diana: "Diana",
  DrMundo: "Dr. Mundo",
  Draven: "Draven",
  Ekko: "Ekko",
  Elise: "Elise",
  Evelynn: "Evelynn",
  Ezreal: "Ezreal",
  Fiddlesticks: "Fiddlesticks",
  Fiora: "Fiora",
  Fizz: "Fizz",
  Galio: "Galio",
  Gangplank: "Gangplank",
  Garen: "Garen",
  Gnar: "Gnar",
  Gragas: "Gragas",
  Graves: "Graves",
  Gwen: "Gwen",
  Hecarim: "Hecarim",
  Heimerdinger: "Heimerdinger",
  Hwei: "Hwei",
  Illaoi: "Illaoi",
  Irelia: "Irelia",
  Ivern: "Ivern",
  Janna: "Janna",
  JarvanIV: "Jarvan IV",
  Jax: "Jax",
  Jayce: "Jayce",
  Jhin: "Jhin",
  Jinx: "Jinx",
  KSante: "K'Santé",
  Kaisa: "Kai'Sa",
  Kalista: "Kalista",
  Karma: "Karma",
  Karthus: "Karthus",
  Kassadin: "Kassadin",
  Katarina: "Katarina",
  Kayle: "Kayle",
  Kayn: "Kayn",
  Kennen: "Kennen",
  Khazix: "Kha'Zix",
  Kindred: "Kindred",
  Kled: "Kled",
  KogMaw: "Kog'Maw",
  Leblanc: "LeBlanc",
  LeeSin: "Lee Sin",
  Leona: "Leona",
  Lillia: "Lillia",
  Lissandra: "Lissandra",
  Locke: "Locke",
  Lucian: "Lucian",
  Lulu: "Lulu",
  Lux: "Lux",
  Malphite: "Malphite",
  Malzahar: "Malzahar",
  Maokai: "Maokai",
  MasterYi: "Maître Yi",
  Mel: "Mel",
  Milio: "Milio",
  MissFortune: "Miss Fortune",
  MonkeyKing: "Wukong",
  Mordekaiser: "Mordekaiser",
  Morgana: "Morgana",
  Naafiri: "Naafiri",
  Nami: "Nami",
  Nasus: "Nasus",
  Nautilus: "Nautilus",
  Neeko: "Neeko",
  Nidalee: "Nidalee",
  Nilah: "Nilah",
  Nocturne: "Nocturne",
  Nunu: "Nunu et Willump",
  Olaf: "Olaf",
  Orianna: "Orianna",
  Ornn: "Ornn",
  Pantheon: "Pantheon",
  Poppy: "Poppy",
  Pyke: "Pyke",
  Qiyana: "Qiyana",
  Quinn: "Quinn",
  Rakan: "Rakan",
  Rammus: "Rammus",
  RekSai: "Rek'Sai",
  Rell: "Rell",
  Renata: "Renata Glasc",
  Renekton: "Renekton",
  Rengar: "Rengar",
  Riven: "Riven",
  Rumble: "Rumble",
  Ryze: "Ryze",
  Samira: "Samira",
  Sejuani: "Sejuani",
  Senna: "Senna",
  Seraphine: "Séraphine",
  Sett: "Sett",
  Shaco: "Shaco",
  Shen: "Shen",
  Shyvana: "Shyvana",
  Singed: "Singed",
  Sion: "Sion",
  Sivir: "Sivir",
  Skarner: "Skarner",
  Smolder: "Smolder",
  Sona: "Sona",
  Soraka: "Soraka",
  Swain: "Swain",
  Sylas: "Sylas",
  Syndra: "Syndra",
  TahmKench: "Tahm Kench",
  Taliyah: "Taliyah",
  Talon: "Talon",
  Taric: "Taric",
  Teemo: "Teemo",
  Thresh: "Thresh",
  Tristana: "Tristana",
  Trundle: "Trundle",
  Tryndamere: "Tryndamere",
  TwistedFate: "Twisted Fate",
  Twitch: "Twitch",
  Udyr: "Udyr",
  Urgot: "Urgot",
  Varus: "Varus",
  Vayne: "Vayne",
  Veigar: "Veigar",
  Velkoz: "Vel'Koz",
  Vex: "Vex",
  Vi: "Vi",
  Viego: "Viego",
  Viktor: "Viktor",
  Vladimir: "Vladimir",
  Volibear: "Volibear",
  Warwick: "Warwick",
  Xayah: "Xayah",
  Xerath: "Xerath",
  XinZhao: "Xin Zhao",
  Yasuo: "Yasuo",
  Yone: "Yone",
  Yorick: "Yorick",
  Yunara: "Yunara",
  Yuumi: "Yuumi",
  Zaahen: "Zaahen",
  Zac: "Zac",
  Zed: "Zed",
  Zeri: "Zeri",
  Ziggs: "Ziggs",
  Zilean: "Zilean",
  Zoe: "Zoé",
  Zyra: "Zyra",
};

/** Identifiant numérique (spectator-v5) vers clé Data Dragon. */
export const CHAMPION_BY_NUMERIC_ID: Record<string, string> = {
  "266": "Aatrox",
  "103": "Ahri",
  "84": "Akali",
  "166": "Akshan",
  "12": "Alistar",
  "799": "Ambessa",
  "32": "Amumu",
  "34": "Anivia",
  "1": "Annie",
  "523": "Aphelios",
  "22": "Ashe",
  "136": "AurelionSol",
  "893": "Aurora",
  "268": "Azir",
  "432": "Bard",
  "200": "Belveth",
  "53": "Blitzcrank",
  "63": "Brand",
  "201": "Braum",
  "233": "Briar",
  "51": "Caitlyn",
  "164": "Camille",
  "69": "Cassiopeia",
  "31": "Chogath",
  "42": "Corki",
  "122": "Darius",
  "131": "Diana",
  "36": "DrMundo",
  "119": "Draven",
  "245": "Ekko",
  "60": "Elise",
  "28": "Evelynn",
  "81": "Ezreal",
  "9": "Fiddlesticks",
  "114": "Fiora",
  "105": "Fizz",
  "3": "Galio",
  "41": "Gangplank",
  "86": "Garen",
  "150": "Gnar",
  "79": "Gragas",
  "104": "Graves",
  "887": "Gwen",
  "120": "Hecarim",
  "74": "Heimerdinger",
  "910": "Hwei",
  "420": "Illaoi",
  "39": "Irelia",
  "427": "Ivern",
  "40": "Janna",
  "59": "JarvanIV",
  "24": "Jax",
  "126": "Jayce",
  "202": "Jhin",
  "222": "Jinx",
  "897": "KSante",
  "145": "Kaisa",
  "429": "Kalista",
  "43": "Karma",
  "30": "Karthus",
  "38": "Kassadin",
  "55": "Katarina",
  "10": "Kayle",
  "141": "Kayn",
  "85": "Kennen",
  "121": "Khazix",
  "203": "Kindred",
  "240": "Kled",
  "96": "KogMaw",
  "7": "Leblanc",
  "64": "LeeSin",
  "89": "Leona",
  "876": "Lillia",
  "127": "Lissandra",
  "805": "Locke",
  "236": "Lucian",
  "117": "Lulu",
  "99": "Lux",
  "54": "Malphite",
  "90": "Malzahar",
  "57": "Maokai",
  "11": "MasterYi",
  "800": "Mel",
  "902": "Milio",
  "21": "MissFortune",
  "62": "MonkeyKing",
  "82": "Mordekaiser",
  "25": "Morgana",
  "950": "Naafiri",
  "267": "Nami",
  "75": "Nasus",
  "111": "Nautilus",
  "518": "Neeko",
  "76": "Nidalee",
  "895": "Nilah",
  "56": "Nocturne",
  "20": "Nunu",
  "2": "Olaf",
  "61": "Orianna",
  "516": "Ornn",
  "80": "Pantheon",
  "78": "Poppy",
  "555": "Pyke",
  "246": "Qiyana",
  "133": "Quinn",
  "497": "Rakan",
  "33": "Rammus",
  "421": "RekSai",
  "526": "Rell",
  "888": "Renata",
  "58": "Renekton",
  "107": "Rengar",
  "92": "Riven",
  "68": "Rumble",
  "13": "Ryze",
  "360": "Samira",
  "113": "Sejuani",
  "235": "Senna",
  "147": "Seraphine",
  "875": "Sett",
  "35": "Shaco",
  "98": "Shen",
  "102": "Shyvana",
  "27": "Singed",
  "14": "Sion",
  "15": "Sivir",
  "72": "Skarner",
  "901": "Smolder",
  "37": "Sona",
  "16": "Soraka",
  "50": "Swain",
  "517": "Sylas",
  "134": "Syndra",
  "223": "TahmKench",
  "163": "Taliyah",
  "91": "Talon",
  "44": "Taric",
  "17": "Teemo",
  "412": "Thresh",
  "18": "Tristana",
  "48": "Trundle",
  "23": "Tryndamere",
  "4": "TwistedFate",
  "29": "Twitch",
  "77": "Udyr",
  "6": "Urgot",
  "110": "Varus",
  "67": "Vayne",
  "45": "Veigar",
  "161": "Velkoz",
  "711": "Vex",
  "254": "Vi",
  "234": "Viego",
  "112": "Viktor",
  "8": "Vladimir",
  "106": "Volibear",
  "19": "Warwick",
  "498": "Xayah",
  "101": "Xerath",
  "5": "XinZhao",
  "157": "Yasuo",
  "777": "Yone",
  "83": "Yorick",
  "804": "Yunara",
  "350": "Yuumi",
  "904": "Zaahen",
  "154": "Zac",
  "238": "Zed",
  "221": "Zeri",
  "115": "Ziggs",
  "26": "Zilean",
  "142": "Zoe",
  "143": "Zyra",
};

/** Normalisation commune : casse et ponctuation retirées. */
function norm(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]/g, "");
}

const BY_NORM: Record<string, string> = Object.fromEntries(
  Object.keys(CHAMPION_NAMES).map((id) => [norm(id), id]),
);

/**
 * Clé Data Dragon canonique pour un championName de l'API. Renvoie l'entrée
 * telle quelle si elle est inconnue : un champion sorti après la dernière
 * synchronisation doit dégrader une icône, pas casser la page.
 */
export function championKey(championName: string): string {
  return BY_NORM[norm(championName)] ?? championName;
}

export function championLabel(championName: string): string {
  return CHAMPION_NAMES[championKey(championName)] ?? championName;
}

export function championKeyFromNumericId(id: number | string): string | null {
  return CHAMPION_BY_NUMERIC_ID[String(id)] ?? null;
}

export const DDRAGON_VERSION = "16.18.1";
